name: telegram-bot-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Or your preferred Python version
  - pip
  - pip:
      - python-telegram-bot==20.7
      # Add any other pip dependencies here, for example:
      # - requests
      # - python-dotenv
