name: Python package

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          conda install pytest

      - name: Run tests
        run: |
          pytest anonxconnect_bot
